#* Docker Compose version
version: '3.9'

#* All services to be used will be declared
services:

  #* Service name
    frontend:
      #* Image to use
      image: node:20.14.2-alpine
      init: true
      #* Directory where you will work
      working_dir: /home/dev
      #* Container name
      container_name: manghi.dev
      command: sh -c "npm i && npm run dev"
      #* Port exhibition
      ports:
        - 4321:4321
      #* Volume where information persists
      volumes:
        - .:/home/dev
      restart: unless-stopped